import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'fr_FR': {
          'Choisissez votre langue': 'Choisissez votre langue',
           "Connectez vous à votre entreprise":"Connectez vous à votre entreprise",
           "Entrer votre adresse mail":"Entrer votre adresse mail",
           "Votre adresse mail":"Votre adresse mail",
           "Entrer votre mot de passe":"Entrer votre mot de passe",
           "Votre mote de passe":"Votre mote de passe",
           "Erreur de connexion vérifier vos informations":"Erreur de connexion vérifier vos informations",
           "Se Connecter":"Se Connecter",
           "Mot de passe oublié ?":"Mot de passe oublié ?",
           "Voulez vous fermer l'application ?":"Voulez vous fermer l'application ?",
           "Oui":"Oui",
           "Non":"Non",
           "Envoyer":"Envoyer",
           "Erreur l'adresse mail n'existe pas.":"Erreur l'adresse mail n'existe pas.",
           "Entrer l' adresse mail du compte":"Entrer l' adresse mail du compte",
           "Code invalid":"Code invalid",
           "Entrer le code que vous avez reçu par mail":"Entrer le code que vous avez reçu par mail",
           "Les mot de passe doivent être identique":"Les mot de passe doivent être identique",
           "Erreur de modification du mot de passe":"Erreur de modification du mot de passe",
           "Confirmez votre mot de passe":"Confirmez votre mot de passe",
           "Nouveau mot de passe":"Nouveau mot de passe",
           "Votre nouveau mot de passe":"Votre nouveau mot de passe",
           "Modifié votre mot de passe":"Modifié votre mot de passe",
           "Free Pay  tableau de bord":"Free Pay  tableau de bord",
           "Clients":"Clients",
           "Free Pay Carte":"Free Pay Carte",
           "Active carte":"Active carte",
           "Revenue du jour":"Revenue du jour",
           "Revenue de la semaine":"Revenue de la semaine",
           "Revenue du mois":"Revenue du mois",
           "Transaction de la journée":"Transaction de la journée",
           "Voir l'historique":"Voir l'historique",
           "Aucune transaction effectuée":"Aucune transaction effectuée",
           "Contactez  +288 93 26 60 04 / +228 92 21 25 30 pour valider votre compte pour profiter de notre service.":"Contactez  +288 93 26 60 04 / +228 92 21 25 30 pour valider votre compte pour profiter de notre service.",
           "Bienvenue":"Bienvenue",
           "Contactez  +288 93 26 60 04 / +228 92 21 25 30 pour valider votre compte":"Contactez  +288 93 26 60 04 / +228 92 21 25 30 pour valider votre compte",
           "Déconnexion":"Déconnexion",
           "Voulez-vous vraiment vous déconnectez":"Voulez-vous vraiment vous déconnectez",
           "Entreprise":"Entreprise",
           "Langue":"Langue",
           "Anglais":"Anglais",
           "Français":"Français",
           "Paramètre du compte":"Paramètre du compte",
           "Valider une transaction":"Valider une transaction",
           "Débité":"Débité",
           "Crédité":"Crédité",
           "Aucune transaction n'à été effectuer avec cette carte.":"Aucune transaction n'à été effectuer avec cette carte.",
           "Date:":"Date:",
           "Activée":"Activée",
           "Désactivée":"Désactivée",
           "Numéro":"Numéro",
           "Montant":"Montant",
           "Info de la carte.":"Info de la carte.",
           "Quartier":"Quartier",
           "Email":"Email",
           "Adresse":"Adresse",
           "Ville":"Ville",
           "Téléphone":"Téléphone",
           "Nom":"Nom",
           "Info personnelle.":"Info personnelle.",
           "Transaction":"Transaction",
           "Détails":"Détails",
           "Voulez-vous supprimé?    Non":"Voulez-vous supprimé?    Non",
           "Sélectionnez un client":"Sélectionnez un client",
           "Veuillez entrer le montant":"Veuillez entrer le montant",
           "Enregistrer":"Enregistrer",
           "La carte à été bien ajouter":"La carte à été bien ajouter",
           "Ajouter une carte":"Ajouter une carte",
           "Cliquez ici pour Scanner la carte.":"Cliquez ici pour Scanner la carte.",
           "Le numéro de la carte":"Le numéro de la carte",
           "Entrer le numéro  ou scanné la carte":"Entrer le numéro  ou scanné la carte",
           "Veuillez entrer le numéro de la carte":"Veuillez entrer le numéro de la carte",
           "Valider":"Valider",
           "La carte à éte bien créditer":"La carte à éte bien créditer",
           "Crédité Free Pay Carte":"Crédité Free Pay Carte",
           "Débité Free Pay Carte":"Débité Free Pay Carte",
           "La carte à éte bien débiter":"La carte à éte bien débiter",
           "Vous n'avez pas de cartes pour l'instant.":"Vous n'avez pas de cartes pour l'instant.",
           "Aucun résultat pour votre recherche":"Aucun résultat pour votre recherche",
           "Entrer le nom du client.":"Entrer le nom du client.",
           "Cliquez ici pour Scanner le ticket.":"Cliquez ici pour Scanner le ticket.",
           "Le numéro du ticket":"Le numéro du ticket",
           "Entrer le numéro  ou scanner le ticket":"Entrer le numéro  ou scanner le ticket",
           "Veuillez entrer le code de la transaction":"Veuillez entrer le code de la transaction",
           "Valider la transaction":"Valider la transaction",
           "Numéro de téléphone":"Numéro de téléphone",
           "Numéro de téléphone invalide":"Numéro de téléphone invalide",
           "Rechercher votre pays":"Rechercher votre pays",
           "Choisissez un identifiant":"Choisissez un identifiant",
           "Identifiant":"Identifiant",
           "Veuillez entrer un identifiant":"Veuillez entrer un identifiant",
           "Veuillez entrer le quartier":"Veuillez entrer le quartier",
           "Veuillez entrer l'email":"Veuillez entrer l'email",
           "Adresse du client":"Adresse du client",
           "Adresse":"Adresse",
           "Veuillez entrer l'adresse":"Veuillez entrer l'adresse",
           "Ville  du client":"Ville  du client",
           "Veuillez entrer la ville":"Veuillez entrer la ville",
           "Nom et prénom du client":"Nom et prénom du client",
           "Le client à été bien ajouter":"Le client à été bien ajouter",
           "Ajouter un client":"Ajouter un client",
           "Vous ne  disposez pas de client pour l'instant.":"Vous ne  disposez pas de client pour l'instant.",
           "Aucun résultat pour votre recherche":"Aucun résultat pour votre recherche",
           "Rechercher un client":"Rechercher un client",
           "Modifier un client":"Modifier un client",
           "Le client à été bien modifier":"Le client à été bien modifier",
           "Modifier":"Modifier",
           "Action indisponible":"Action indisponible",
           "Modifier l'identifiant":"Modifier l'identifiant",
           "Informations client":"Informations client",
           "Historiques des transactions":"Historiques des transactions",
           "Mois":"Mois",
           "Semaine":"Semaine",
           "Jour":"Jour",
           "Votre Compte à été bien  modifier":"Votre Compte à été bien  modifier",
           "Erreur":"Erreur",
           "Modifier votre compte":"Modifier votre compte",
           "Le nom de votre entreprise":"Le nom de votre entreprise",
           "Nom de l'entreprise":"Nom de l'entreprise",
           "Adresse de l'entreprise":"Adresse de l'entreprise",
           "Optionnel":"Optionnel",
           "Raison sociale":"Raison sociale",
           "Mot de passe":"Mot de passe",
           "Choisissez un  Mot de passe":"Choisissez un  Mot de passe",
           "Une petite description de votre entreprise":"Une petite description de votre entreprise",
           "Une petite description":"Une petite description",
           "Le mot de passe à été bien modifier":"Le mot de passe à été bien modifier",
           "Erreur de modification du mot de passe":"Erreur de modification du mot de passe",
           "Modifier le mot de passe":"Modifier le mot de passe",
           "Entrer le nouveau mot de passe":"Entrer le nouveau mot de passe",
           "Nouveau mot de passe":"Nouveau mot de passe",
           "Montant restant sur les  cartes:":"Montant restant sur les  cartes:",
           "Montant total des  cartes:":"Montant total des  cartes:",
           "Image du profil mise à jour":"Image du profil mise à jour",
           "Notifications":"Notifications",
           "Tableau de bord":"Tableau de bord",
            "Montant:":"Montant:",
            "Numéro:":"Numéro:",
            
            

        },
        'en_US': {
          "Numéro:":"Number:",
           "Montant:":"Amount:",
          "Tableau de bord":"Dashboard",
          "Notifications":"Notifications",
          "Image du profil mise à jour":"Updated profile picture",
          "Montant total des  cartes:":"Total amount of cards:",
          "Montant restant sur les  cartes:":"Amount remaining on the cards:",
          "Nouveau mot de passe":"New Password",
          "Entrer le nouveau mot de passe":"Enter new password",
          "Modifier le mot de passe":"change the password",
          "Erreur de modification du mot de passe":"Password change error",
          "Le mot de passe à été bien modifier":"The password has been changed correctly",
          "Une petite description":"A short description",
          "Une petite description de votre entreprise":"A brief description of your business",
          "Choisissez un  Mot de passe":"Choose a password",
          "Mot de passe":"Password",
          "Raison sociale":"Social reason",
          "Optionnel":"Optional",
          "Adresse de l'entreprise":"Company address",
          "Nom de l'entreprise":"Company Name",
          "Le nom de votre entreprise":"Your business name",
          "Modifier votre compte":"Modify our account",
          "Erreur":"Error",
          "Votre Compte à été bien  modifier":"Your account has been successfully modified",
          "Jour":"Day",
          "Semaine":"Week",
          "Mois":"Month",
          "Historiques des transactions":"Transaction history",
          "Informations client":"Customer information",
          "Modifier l'identifiant":"Edit identifier",
          "Action indisponible":"not available",
          "Modifier":"Edit",
          "Le client à été bien modifier":"The client has been modified",
          "Modifier un client":"Edit a customer",
          "Rechercher un client":"Search a customer",
          "Aucun résultat pour votre recherche":"No result for your search",
          "Vous ne  disposez pas de client pour l'instant.":"You don't have a customer yet.",
          "Ajouter un client":"Add a customer",
          "Le client à été bien ajouter":"The customer has been added",
          "Nom et prénom du client":"Customer's first and last name",
          "Veuillez entrer la ville":"Please enter the city",
          "Ville  du client":"Customer's city",
          "Veuillez entrer l'adresse":"Please enter the address",
          "Adresse":"Address",
          "Adresse du client":"Customer address",
          "Veuillez entrer l'email":"Please enter email",
          "Veuillez entrer le quartier":"Please enter the neighborhood",
          "Veuillez entrer un identifiant":"Please enter a user identifier",
          "Identifiant":"Identifier",
          "Choisissez un identifiant":"choose a user identifier",
          "Rechercher votre pays":"Find your country",
          "Numéro de téléphone invalide":"Invalid phone number",
          "Numéro de téléphone":"Phone number",
          "Valider la transaction":"Validate the transaction",
          "Veuillez entrer le code de la transaction":"Please enter the transaction code",
          "Entrer le numéro  ou scanner le ticket":"Enter the number or scan the ticket",
          "Le numéro du ticket":"The ticket number",
          "Cliquez ici pour Scanner le ticket.":"Click here to Scan the ticket.",
          "Entrer le nom du client.":"Enter the customer's name.",
          "Aucun résultat pour votre recherche":"No result for your search",
          "Vous n'avez pas de cartes pour l'instant.":"You don't have any cards yet.",
          "La carte à éte bien débiter":"The card has been debited",
          "Débité Free Pay Carte":"Debited Free Pay Card",
          "Crédité Free Pay Carte":"Credited Free Pay Card",
          "La carte à éte bien créditer":"The card has been credited correctly",
          "Valider":"Save",
          "Veuillez entrer le numéro de la carte":"Please enter card number",
          "Entrer le numéro  ou scanné la carte":"Enter the number or scan the card",
          "Le numéro de la carte":"The card number",
          "Cliquez ici pour Scanner la carte.":"Click here to scan the card.",
          "Ajouter une carte":"Add a card",
          "La carte à été bien ajouter":"The card has been added",
          "Enregistrer":"Save",
          "Veuillez entrer le montant":"Please enter the amount",
          "Sélectionnez un client":"Select a customer",
          "Voulez-vous supprimé?    Non":"Do you want deleted? No",
          "Détails":"Details",
          "Transaction":"Transaction",
          "Info personnelle.":"Personal info.",
          "Nom":"Name",
          "Téléphone":"Phone",
          "Ville":"City",
          "Adresse":"Address",
          "Email":"E-mail",
          "Quartier":"Neighborhood",
          "Info de la carte.":"Card info",
          "Montant":"Amount",
          "Numéro":"Number",
          "Désactivée":"Disabled",
          "Activée":"Activated",
          "Date:":"Date:",
          "Aucune transaction n'à été effectuer avec cette carte.":"No transaction has been made with this card.",
          "Crédité":"Credited",
          "Débité":"Debited",
          "Valider une transaction":"Validate a transaction",
          "Paramètre du compte":"Account setting",
          "Français":"French",
          "Anglais":"English",
          "Langue":"Language",
          "Entreprise":"Business",
          "Voulez-vous vraiment vous déconnectez":"Do you really want to disconnect",
          "Contactez  +288 93 26 60 04 / +228 92 21 25 30 pour valider votre compte":"Contact +288 93 26 60 04 / +228 92 21 25 30 to validate your account",
            "Déconnexion":"Logout",
          "Free Pay  tableau de bord":"Free Pay Dashboard",
          "Contactez  +288 93 26 60 04 / +228 92 21 25 30 pour valider votre compte pour profiter de notre service.":"Contact +288 93 26 60 04 / +228 92 21 25 30 to validate your account to take advantage of our service.",
          "Bienvenue":"Welcome",
          "Aucune transaction effectuée":"No transaction made",
          "Voir l'historique":"See history",
          "Transaction de la journée":"Trade of the day",
          "Revenue du mois":"Income of the month",
          "Revenue de la semaine":"Income of the week",
          "Revenue du jour":"Income of the day",
          "Active carte":"Active card",
          "Free Pay Carte":"Free Pay Card",
          "Clients":"Customer",
          "Free Pay  Dashboard":"Free Pay  Dashboard",
          "Modifié votre mot de passe":"Changed your password",
          "Votre nouveau mot de passe":"Your new password",
          "Nouveau mot de passe":"New Password",
          "Confirmez votre mot de passe":"Confirm your password",
          "Erreur de modification du mot de passe":"Password change error",
          "Les mot de passe doivent être identique":"Passwords must be the same",
          "Entrer le code que vous avez reçu par mail":"Enter the code you received by email",
          "Code invalid":"Code invalid",
          "Entrer l' adresse mail du compte":"Enter the account email address",
          "Erreur l'adresse mail n'existe pas.":"Error the email address does not exist.",
          "Envoyer":"Send",
          "Non":"No",
          "Oui":"Yes",
          "Voulez vous fermer l'application ?":"Do you want to close the application?",
          "Mot de passe oublié ?":"Forgot your password ?",
          "Se Connecter":"Login",
          "Erreur de connexion vérifier vos informations":"Connection error verify your information",
          "Votre mote de passe":"Your password",
          "Entrer votre mot de passe":"Enter your password",
          "Votre adresse mail":"Your email",
          'Choisissez votre langue': 'Choose your language',
          "Connectez vous à votre entreprise":"Connect to your business",
          "Entrer votre adresse mail":"Enter your email address",
        },
      };
}
